import { Link } from "react-router-dom";

const Blog = () => {
  const blogPosts = [
    {
      title: "Introducing StorySparkAI v2.0",
      description:
        "Discover the new features we've added to help you craft better stories faster.",
      link: "/blog/1",
      tag: "Updates",
      readTime: "3 min read",
    },
    {
      title: "How to Overcome Writer's Block with AI",
      description:
        "Learn practical techniques to use AI as a collaborative brainstorming partner.",
      link: "/blog/2",
      tag: "Writing Tips",
      readTime: "5 min read",
    },
    {
      title: "Community Spotlight: Outstanding Stories",
      description:
        "Highlighting some of the best and most creative stories generated by our users.",
      link: "/blog/3",
      tag: "Community",
      readTime: "4 min read",
    },
  ];

  return (
    <div className="min-h-screen bg-white text-slate-900 dark:bg-[#0b1329] dark:text-white px-6 py-12 transition-colors duration-300">
      <div className="max-w-6xl mx-auto">

        {/* HERO SECTION */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold mb-4">StorySpark Blog</h1>
          <p className="text-lg text-slate-600 dark:text-gray-300 max-w-2xl mx-auto">
            Insights, updates, and storytelling inspiration from the StorySpark AI community.
          </p>

          {/* CATEGORY PILLS */}
          <div className="flex flex-wrap justify-center gap-3 mt-6">
            {["All", "AI Writing", "Updates", "Community", "Tips"].map((cat) => (
              <span
                key={cat}
                className="px-4 py-2 text-sm rounded-full border border-gray-300 dark:border-gray-700 hover:bg-blue-500 hover:text-white cursor-pointer transition"
              >
                {cat}
              </span>
            ))}
          </div>
        </div>

        {/* FEATURED SECTION */}
        <div className="mb-10 p-8 rounded-2xl bg-gradient-to-r from-blue-600 to-purple-600 text-white shadow-lg">
          <h2 className="text-2xl font-bold mb-2">🔥 Featured Article</h2>
          <p className="text-lg font-semibold">
            Introducing StorySparkAI v2.0 — A new era of AI storytelling
          </p>
          <Link
            to="/blog/1"
            className="inline-block mt-4 px-5 py-2 bg-white text-blue-600 font-semibold rounded-full hover:bg-gray-100 transition"
          >
            Read Now →
          </Link>
        </div>

        {/* BLOG GRID */}
        <div className="grid md:grid-cols-3 gap-8">
          {blogPosts.map((post, index) => (
            <div
              key={index}
              className="group p-6 rounded-2xl border border-gray-200 dark:border-gray-800 bg-white dark:bg-zinc-900 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300"
            >
              {/* TAG */}
              <span className="text-xs px-3 py-1 rounded-full bg-blue-100 text-blue-600 dark:bg-blue-900 dark:text-blue-300">
                {post.tag}
              </span>

              <h3 className="text-xl font-semibold mt-4 mb-2 group-hover:text-blue-500 transition">
                {post.title}
              </h3>

              <p className="text-slate-600 dark:text-gray-300 text-sm leading-relaxed">
                {post.description}
              </p>

              <div className="flex justify-between items-center mt-4 text-xs text-gray-500 dark:text-gray-400">
                <span>{post.readTime}</span>
              </div>

              <Link
                to={post.link}
                className="inline-block mt-4 text-blue-500 font-medium hover:underline"
              >
                Read More →
              </Link>
            </div>
          ))}
        </div>

        {/* BACK BUTTON */}
        <div className="text-center mt-12">
          <Link
            to="/"
            className="px-6 py-3 bg-blue-500 text-white font-semibold text-lg rounded-full shadow-md hover:bg-blue-600 transition"
          >
            ⬅ Back to Home
          </Link>
        </div>
      </div>
    </div>
  );
};

export default Blog;